version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
    command: sh -c './wait-for localhost:3306 -- npm start'
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: car_rental
      MYSQL_USER: root
      MYSQL_PASSWORD: Kulamula!
      MYSQL_ROOT_PASSWORD: Kulamula!