version: '3.7'
services:
  api:
    build: ./

    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - database
  database:
    container_name: "db"
    image: "mysql:8.0"
    environment:
      MYSQL_USER: user1
      MYSQL_PASSWORD: password1
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_DATABASE: generatenumberldb
    ports:
      - "3307:3306"
    restart: always
