version: '3'
services:
  api:
    build: ./generate-number-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    container_name: "database"
    image: "mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_DATABASE: generatenumberldb
    ports:
      - "3307:3306"

